# https://taskfile.dev

version: "3"

vars:
    PROJECT_NAME: myos

    OUTPUT_DIR: build
    X86_DIR: x86
    X86_DIR_FILES: |
        kernel
        multiboot_header
        extfunc
    FS_DIR: fs

    RUST_CODE_FILE: target/i686-{{$.PROJECT_NAME}}/debug/lib{{$.PROJECT_NAME}}.a
    KERNEL_FILE: kernel.bin
    LINKER_FILE: linker.ld
    OS_IMAGE_FILE: os.iso
    GRUB_FILE: grub.cfg
    FS_FILE: fs.img

    ASM_EX: .asm
    OBJ_EX: .o

    NASM: nasm -f elf -o
    LD: ld -m elf_i386 -v -nostdlib -o {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} -T {{$.LINKER_FILE}}
    QEMU_DEVICES: |
        qemu-xhci
        ahci,id=ahci
        ide-cd,drive=disk,bus=ahci.0
    QEMU_DRIVES: |
        id=disk,file={{$.OUTPUT_DIR}}/{{$.OS_IMAGE_FILE}},if=none,format=raw
    QEMU: qemu-system-i386 -no-reboot -no-shutdown -m 4G {{range .QEMU_DRIVES | splitLines -}}{{if .}}-drive {{.}} {{end}}{{end -}} {{range .QEMU_DEVICES | splitLines -}}{{if .}}-device {{.}} {{end}}{{end -}} -boot order=d -serial mon:stdio


tasks:
    init:
        cmds:
            - mkdir {{$.OUTPUT_DIR}}

    clear:
        cmds:
            - rm -rf {{$.OUTPUT_DIR}}/*

    rustb:
        deps: [clear]
        cmds:
            - cargo xbuild

    makeelf:
        deps: [rustb]
        cmds:
            - |
                {{range .X86_DIR_FILES | splitLines -}}
                {{if .}}{{$.NASM}} {{$.OUTPUT_DIR}}/{{.}}{{$.OBJ_EX}} {{$.X86_DIR}}/{{.}}{{$.ASM_EX}}{{end}}
                {{end -}}
                {{$.LD}} {{range .X86_DIR_FILES | splitLines -}}{{if .}}{{$.OUTPUT_DIR}}/{{.}}{{$.OBJ_EX}}{{end}} {{end -}}{{$.RUST_CODE_FILE}}

    makefs:
        dir: "{{$.FS_DIR}}"
        cmds:
            - dd if=/dev/zero of=../{{$.OUTPUT_DIR}}/{{$.FS_FILE}} bs=1M count=1 # file size: 1MB
            - sudo mkfs.vfat -v -c -F 32 ../{{$.OUTPUT_DIR}}/{{$.FS_FILE}} # format for FAT32
            - sudo losetup /dev/loop0 ../{{$.OUTPUT_DIR}}/{{$.FS_FILE}}
            - sudo mount /dev/loop0 /mnt
            - find . -type f -exec sudo cp --parents {} /mnt \;
            - sudo umount /mnt
            - sudo losetup -d /dev/loop0


    build:
        cmds:
            - task: makeelf
            - task: makefs
            - mkdir -p {{$.OUTPUT_DIR}}/isofiles/boot/grub
            - cp {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} {{$.OUTPUT_DIR}}/isofiles/boot/
            - cp {{$.OUTPUT_DIR}}/{{$.FS_FILE}} {{$.OUTPUT_DIR}}/isofiles/
            - cp {{$.GRUB_FILE}} {{$.OUTPUT_DIR}}/isofiles/boot/grub/
            - grub-mkrescue -o {{$.OUTPUT_DIR}}/{{$.OS_IMAGE_FILE}} {{$.OUTPUT_DIR}}/isofiles 2> /dev/null
            - rm -r {{$.OUTPUT_DIR}}/isofiles

    run:
        deps: [build]
        cmds:
            - "{{$.QEMU}}"

    debug:
        deps: [build]
        cmds:
            - task: makehdd
            - "{{$.QEMU}} -s -S"

    gdb:
        cmds:
            - rust-gdb "{{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}}" -ex "target remote localhost:1234"

    dump:
        cmds:
            - objdump -d {{$.OUTPUT_DIR}}/{{$.KERNEL_FILE}} > dump.txt

    # write to usb
    write:
        deps: [build]
        cmds:
            - sudo dd if={{$.OUTPUT_DIR}}/{{$.OS_IMAGE_FILE}} of=/dev/sdc bs=1M

    # TODO: faile to compile
    #test:
    #    cmds:
    #        - cargo test -Z build-std=core --no-run